# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0941c0ffcb7c08fcadc73770935c7ef975f4aff4a6a09a602a32ba3696cf1ab7405d0ef0ab40f2e965114ec19b7d3a68aab6fc40176c711cbdb3ac6a82851d9

test:
  secret_key_base: 6be9af20ddc0fe8b0f82c71c6ba74a1d7481ccd3f74b69fd0dfd8b81bed692574a7127e56762dcb867ecd70541966dde17f66c629de46bdf16bece0dedf836a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
